name: Build and Publish Keycloak Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'keycloak-scripts/**'
      - 'keycloak-providers/**'
      - 'secrets2env.sh'
      - '.forgejo/workflows/build.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'keycloak-scripts/**'
      - 'keycloak-providers/**'
      - 'secrets2env.sh'
      - '.forgejo/workflows/build.yaml'

jobs:
  build:
    uses: stackdrift-images/ci-templates/.forgejo/workflows/docker-build.yaml@main
    with:
      image_name: codeberg.org/stackdrift-images/keycloak
      upstream_image_search: quay.io/keycloak/keycloak
      upstream_name_short: keycloak
    secrets:
      registry_password: ${{ secrets.REGISTRY_DEPLOY_KEY }}
