name: Build and Publish Keycloak Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: stackdrift
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker CLI
        run: |
          set -e
          if ! command -v docker &> /dev/null; then
            apt-get update
            apt-get install -y ca-certificates curl
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
            chmod a+r /etc/apt/keyrings/docker.asc
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt-get update
            apt-get install -y docker-ce-cli
          else
            echo "Docker CLI is already installed."
          fi

      - name: Login to Codeberg Container Registry
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: stackdrift
          password: ${{ secrets.REGISTRY_DEPLOY_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            codeberg.org/stackdrift-images/keycloak:latest
            codeberg.org/stackdrift-images/keycloak:26.3
